version: '3'
services:

#my-sql
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=@Mandrakalam1
    - MYSQL_DATABASE=ecommerce
    network_mode: host
    volumes:
    - ./data/mysql:/var/lib/mysql

#Eureka-Server
  eureka-server:
    image: gcr.io/divine-bloom-383508/dockerimage-eurekaservice
    container_name: eureka-server
    restart: always
    network_mode: host
    environment:
    - spring.application.name=eureka-server
    - server.port=8761
    - eureka.client.register-with-eureka=false
    - eureka.client.fetch-registry=false
    - spring.zipkin.base-url=http://localhost:9411
    - spring.sleuth.sampler.probability=1.0
    

#Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    network_mode: host
    restart: always
    
#elastic search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    restart: on-failure
    environment:
     - bootstrap.memory_lock=true
     - ES_JAVA_OPTS=-Xms512m -Xmx512m
     - discovery.type=single-node
     - xpack.security.enabled=false
     - xpack.security.enrollment.enabled=false
     - xpack.security.http.ssl.enabled=false
     - ingest.geoip.downloader.enabled=false
     - http.host=0.0.0.0
     - transport.host=0.0.0.0
    ulimits:
     memlock:
       soft: -1
       hard: -1
    volumes:
     - ./data/elastic:/var/lib/elasticsearch/data
    network_mode: host
 
#redis 
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    network_mode: host  
  
 
#rabbit-mq
  rabbitmq:
    image: rabbitmq:3.11-management
    network_mode: host
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest    

  
#user-service
  user-service:
    image: gcr.io/divine-bloom-383508/dockerimage-userservice
    container_name: user-service
    network_mode: host
    restart: always
    environment:
    - spring.application.name=user-service
    - server.port=8000
    - spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
    - spring.datasource.username=root
    - spring.datasource.password=@Mandrakalam1
    - logging.level.org.springframework=debug
    - spring.jpa.show-sql=true
    - spring.jpa.hibernate.ddl-auto=update
    - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    - eureka.client.service-url.default-zone=http://localhost:8761/eureka
    - spring.zipkin.base-url=http://localhost:9411
    - spring.sleuth.sampler.probability=1.0 
    depends_on:
    - mysql-db
    - eureka-server
    - zipkin

#product-service   
  product-service:
    image: gcr.io/divine-bloom-383508/dockerimage-productservice
    container_name: product-service
    restart: always
    depends_on: 
      - elasticsearch
      - redis
      - eureka-server
      - zipkin
    environment:
    - spring.application.name=product-service
    - server.port=8001
    - spring.data.elastic-search.cluster-nodes=http://localhost:9200
    - spring.zipkin.base-url=http://localhost:9411
    - spring.sleuth.sampler.probability=1.0 
    - logging.level.org.springframework=debug
    - eureka.client.service-url.default-zone=http://localhost:8761/eureka
    - spring.cache.type=redis
    - spring.data.redis.host=localhost
    - spring.data.redis.port=6379
    - spring.cache.redis.cache-null-values=true
    network_mode: host  
    
    
#cart-service
  cart-service:
    image: gcr.io/divine-bloom-383508/dockerimage-cartservice
    container_name: cart-service
    restart: always
    network_mode: host
    environment:
    - spring.application.name=cart-service
    - server.port=8002
    - spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
    - spring.datasource.username=root
    - spring.datasource.password=@Mandrakalam1
    - logging.level.org.springframework=debug
    - spring.jpa.show-sql=true
    - spring.jpa.hibernate.ddl-auto=update
    - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    - eureka.client.service-url.default-zone=http://localhost:8761/eureka
    - spring.zipkin.base-url=http://localhost:9411
    - spring.sleuth.sampler.probability=1.0 
    depends_on:
    - mysql-db
    - eureka-server
    - zipkin    
    

#order-service
  order-service:
    image: gcr.io/divine-bloom-383508/dockerimage-orderservice
    container_name: order-service
    restart: always
    network_mode: host
    environment:
    - spring.application.name=order-service
    - server.port=8003
    - spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
    - spring.datasource.username=root
    - spring.datasource.password=@Mandrakalam1
    - logging.level.org.springframework=debug
    - spring.jpa.show-sql=true
    - spring.jpa.hibernate.ddl-auto=update
    - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    - eureka.client.service-url.default-zone=http://localhost:8761/eureka
    - spring.zipkin.base-url=http://localhost:9411
    - spring.sleuth.sampler.probability=1.0 
    depends_on:
    - mysql-db
    - eureka-server
    - zipkin

#notification-service
  notification-service:
    image: gcr.io/divine-bloom-383508/dockerimage-notificationservice
    container_name: notification-service
    restart: always
    network_mode: host
    environment:
    - spring.application.name=notification-service
    - server.port=8004
    - spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
    - spring.datasource.username=root
    - spring.datasource.password=@Mandrakalam1
    - logging.level.org.springframework=debug
    - spring.jpa.show-sql=true
    - spring.jpa.hibernate.ddl-auto=update
    - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    - eureka.client.service-url.default-zone=http://localhost:8761/eureka
    - spring.zipkin.base-url=http://localhost:9411
    - spring.sleuth.sampler.probability=1.0 
    depends_on:
    - mysql-db
    - eureka-server
    - zipkin        

#email-service
  email-service:
    image: gcr.io/divine-bloom-383508/dockerimage-emailservice
    container_name: email-service
    restart: always
    network_mode: host
    environment:
    - spring.application.name=email-service
    - server.port=8005
    - spring.mail.host=smtp.gmail.com
    - spring.mail.port=587
    - spring.mail.username=appecommerceamal@gmail.com
    - spring.mail.password=gvyrxwzohfiqppov
    - spring.mail.properties.mail.smtp.auth=true
    - spring.mail.properties.mail.smtp.starttls.enable=true
    - eureka.client.service-url.default-zone=http://localhost:8761/eureka
    - spring.zipkin.base-url=http://localhost:9411
    - spring.sleuth.sampler.probability=1.0 
    depends_on:
    - eureka-server
    - zipkin 
    

#api-gateway
  apigateway-service:
    image: gcr.io/divine-bloom-383508/dockerimage-apigatewayservice
    container_name: apigateway-service
    restart: always 
    network_mode: host
    environment:
    - spring.application.name=api-gateway
    - server.port=8765
    - eureka.client.service-url.default-zone=http://localhost:8761/eureka
    - spring.cloud.gateway.discovery.locator.enabled=true
    - spring.cloud.gateway.discovery.locator.lower-case-service-id=true
    - logging.level.org.springframework=debug
    - spring.zipkin.base-url=http://localhost:9411
    - spring.sleuth.sampler.probability=1.0 
    depends_on:
    - eureka-server
    - zipkin 
  
 