// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLJ-t8ONy145e30ulCU3JP-cN9nsAkYiw',
    appId: '1:784834077002:web:a65fc6c690f704a65ea1b3',
    messagingSenderId: '784834077002',
    projectId: 'divine-bloom-383508',
    authDomain: 'divine-bloom-383508.firebaseapp.com',
    storageBucket: 'divine-bloom-383508.appspot.com',
    measurementId: 'G-KT5H8QVB0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-2MK6VE2umM90eXWYh_6a5UYAfuj06rU',
    appId: '1:784834077002:android:9a6c259aa6d87edb5ea1b3',
    messagingSenderId: '784834077002',
    projectId: 'divine-bloom-383508',
    storageBucket: 'divine-bloom-383508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYEDtSGUKrBQ9S0Y4Sc0ojoijUpIokIuA',
    appId: '1:784834077002:ios:e870311aa49ed43e5ea1b3',
    messagingSenderId: '784834077002',
    projectId: 'divine-bloom-383508',
    storageBucket: 'divine-bloom-383508.appspot.com',
    iosClientId: '784834077002-jrcp5kjbtpfsdljpiq281mscikd3suhv.apps.googleusercontent.com',
    iosBundleId: 'com.simpleonlinestore.simpleOnlineStore',
  );
}
